-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 20:58:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema recipes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recipes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recipes` DEFAULT CHARACTER SET utf8 ;
USE `recipes` ;

-- -----------------------------------------------------
-- Table `recipes`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `recipes`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`dish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `recipes`.`favourite_recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`favourite_recipes` (
  `user_category_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`user_category_id`, `recipe_id`),
  INDEX `fk_user_has_recipe_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  INDEX `fk_user_has_recipe_user1_idx` (`user_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_recipe_user1`
    FOREIGN KEY (`user_category_id`)
    REFERENCES `recipes`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_recipe_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipes`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `recipes`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `dish_id` INT NOT NULL,
  `author_id` INT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(511) NULL,
  `cook_time` TIME NOT NULL,
  `servings` INT NOT NULL,
  `image_id` VARCHAR(36) NULL COMMENT 'image is optional in recipes, we store only if, image is not held in db',
  PRIMARY KEY (`id`),
  INDEX `fk_recipe_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_recipe_dish1_idx` (`dish_id` ASC) VISIBLE,
  INDEX `fk_recipe_user1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `recipes`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `recipes`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_user1`
    FOREIGN KEY (`author_id`)
    REFERENCES `recipes`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `recipes`.`recipe_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`recipe_rating` (
  `recipe_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `user_id`),
  INDEX `fk_recipe_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_recipe_has_user_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_has_user_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipes`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipes`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `recipes`.`recipe_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`recipe_review` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`, `recipe_id`, `date`),
  INDEX `fk_user_has_recipe_recipe2_idx` (`recipe_id` ASC) VISIBLE,
  INDEX `fk_user_has_recipe_user2_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_recipe_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `recipes`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_recipe_recipe2`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipes`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `recipes`.`recipe_step`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`recipe_step` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_recipe_step_recipe1_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_step_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `recipes`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `recipes`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`registration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `token` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `recipes`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `recipes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipes`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `activate_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_user_category_idx` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `recipes`.`role` (`id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION);
